spring:
  profiles:
    active: default
promed:
  url: "https://localhost:1234/"
  login: "test_login"
  password: "test_password"
  lpu:
    id: "12345678"
medsys:
  url: "http://localhost:8090/"
  token: "test-token"
cron:
  schedule: "* 12 12 * * *"
